// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ReactorDummyFactory.cs" company="Naos Project">
//    Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package Naos.Build.Conventions.VisualStudioProjectTemplates.Domain.Test (1.55.30)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Reactor.Domain.Test
{
    using System;

    using FakeItEasy;

    using OBeautifulCode.AutoFakeItEasy;

    /// <summary>
    /// A Dummy Factory for types in <see cref="Naos.Reactor.Domain"/>.
    /// </summary>
#if !NaosReactorRecipesProject
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Naos.Reactor.Domain.Test", "See package version number")]
#endif
    public class ReactorDummyFactory : DefaultReactorDummyFactory
    {
        public ReactorDummyFactory()
        {
            /* Add any overriding or custom registrations here. */
        }
    }
}
