// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Reaction.cs" company="Naos Project">
//    Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Reactor.Domain
{
    using System;
    using System.Collections.Generic;
    using Naos.Database.Domain;
    using OBeautifulCode.Assertion.Recipes;
    using OBeautifulCode.Representation.System;
    using OBeautifulCode.Type;

    /// <summary>
    /// Generated by a <see cref="RegisteredReaction"/> finding records to handle.
    /// </summary>
    public partial class Reaction : IModelViaCodeGen, IHaveStringId
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Reaction"/> class.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="streamRepresentationToInternalRecordIdsMap">The <see cref="IStreamRepresentation"/> to list of internal record identifiers that were evaluated by the reaction.</param>
        public Reaction(
            string id,
            IReadOnlyDictionary<IStreamRepresentation, IReadOnlyList<long>> streamRepresentationToInternalRecordIdsMap)
        {
            id.MustForArg(nameof(id)).NotBeNullNorWhiteSpace();
            streamRepresentationToInternalRecordIdsMap.MustForArg(nameof(streamRepresentationToInternalRecordIdsMap)).NotBeNullNorEmptyDictionaryNorContainAnyNullValues();

            this.Id = id;
            this.StreamRepresentationToInternalRecordIdsMap = streamRepresentationToInternalRecordIdsMap;
        }

        /// <inheritdoc />
        public string Id { get; private set; }

        /// <summary>
        /// The <see cref="IStreamRepresentation"/> to list of internal record identifiers that were evaluated by the reaction.
        /// </summary>
        public IReadOnlyDictionary<IStreamRepresentation, IReadOnlyList<long>> StreamRepresentationToInternalRecordIdsMap { get; private set; }
    }
}
